# Use Node.js LTS
FROM node:20-alpine

WORKDIR /app

# Copy dependencies manifests
COPY package.json pnpm-lock.yaml ./
COPY prisma ./prisma

# Install pnpm and dependencies
RUN npm install -g pnpm && pnpm install

# Copy app source
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Expose NestJS port
EXPOSE 3000

CMD ["pnpm", "start:dev"]